### ISSUE TITLE
Endgame checklist

### ISSUE THREAD

**Issue by medallyon** [sprague-JR/GMTKGameJam#1]
- [x] textures
- [x] sounds
- [x] intro splash screen
- [x] "win/loss" screen
- [ ] design 2 main mazes / levels

start trying to build by 6:30PM
